import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/globals.scss';
import { ClerkProvider } from '@clerk/nextjs';
import Header from '@/components/layout/Header/Header';
import { ScrollArea } from '@/components/ui/scroll-area';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className={`flex min-h-[100dvh] w-full flex-col`}>
            <Header />
            <div className={`flex-1 flex-col`}>
              <div className={`bg-slate-200 p-4`}>
                <ScrollArea className="bg-mint-cream h-[calc(100dvh-4rem)] w-full rounded p-4 shadow-xl">
                  {children}
                </ScrollArea>
              </div>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
